### ISSUE TITLE
Broken Pipe Err no 32 when using HAProxy with Flask

### ISSUE THREAD

**Issue by gkeswani92** [gkeswani92/Distributed-Cloud-Service#1]
127.0.0.1 - - [13/Apr/2016 00:32:24] "HEAD / HTTP/1.0" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 186, in execute
    write(b'')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 152, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

**Comment by gkeswani92** [comment]
Try adding methods = ["HEAD"] on the index page

**Comment by gkeswani92** [comment]
Not needed any more 💃
